import "@/styles/globals.css";
import ClientBody from "./ClientBody";

export const metadata = {
	title: "Moniveo",
	description: "Generated by Moniveo",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<ClientBody>
				{children}
			</ClientBody>
		</html>
	);
}
