import "@/styles/globals.css";
import NavbarContainer from "@/components/Navbar/NavbarContainer";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Moniveo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavbarContainer />
        {children}
        <Footer />
      </body>
    </html>
  );
}
